### ISSUE TITLE
Had to update cstdint.hpp to boost 1.55 version for compiling this

### ISSUE THREAD

**Issue by lmedagoda** [rock-core/tools-service_discovery#2]
Same issue as this (2 years old): https://github.com/Valloric/YouCompleteMe/issues/513

I applied this to fix it: https://svn.boost.org/trac/boost/changeset/84950

Looks like an issue with boost 1.54, which is fixed in 1.55 (a change in checking the version of glibc). The ubuntu version is 1.54 so it had this issue.

**Comment by 2maz** [comment]
Can you provide more details on your case: os version (e.g. cat /etc/lsb_release) and the boost version detected by cmake when building this package.
FYI: I am building on Ubuntu 14.04 64bit and boost 1.54 (default)  without problems.

**Comment by lmedagoda** [comment]
It appears to occur from glibc 2.18. 2.19 is the current release for ubuntu. It's an optional upgrade according to the launchpad:

https://launchpad.net/ubuntu/trusty/amd64/libc-dev-bin

OS: Ubuntu 14.04.3 LTS 64bit
Glibc version (which the fix depends on): ldd (Ubuntu EGLIBC 2.19-0ubuntu6.6) 2.19
Boost in cmake: tools/service_discovery/build/CMakeCache.txt:Boost_VERSION:INTERNAL=105400

**Comment by 2maz** [comment]
Not sure I got the complete picture: the error occurred with libc-dev-bin 2.18 and your fix was to upgrade to libc-dev-bin 2.19 AND change boost/cstdint.hpp?!

**Comment by lmedagoda** [comment]
No, sorry I wasn't clear. I looked at that bug from a different source (Valloric/YouCompleteMe#513). It mentions that this problem occurs from glibc 2.18.

I happen to have glibc 2.19, probably due to an automatic update.

My fix was simply to change boost/cstdint.hpp from the 1.54 version to the 1.55 version.

**Comment by 2maz** [comment]
Can you provide the log files for the error case: <autoproj_root>/install/log/tools/service_discovery-configure  and -build !?

**Comment by lmedagoda** [comment]
From install/log/tools/service_discovery-configure.log : 


2015-08-17 17:19:34 +0200: running
    cmake -DCMAKE_INSTALL_PREFIX=/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install -DCMAKE_MODULE_PATH= -DRUBY_EXECUTABLE=/usr/bin/ruby1.9.1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON /home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/service_discovery
with environment:
  'AUTOPROJ_CURRENT_ROOT'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf'
  'CLUTTER_IM_MODULE'='xim'
  'CMAKE_PREFIX_PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install'
  'COLORTERM'='gnome-terminal'
  'COMPIZ_CONFIG_PROFILE'='ubuntu'
  'DBUS_SESSION_BUS_ADDRESS'='unix:abstract=/tmp/dbus-zj2E1dWZws'
  'DEFAULTS_PATH'='/usr/share/gconf/ubuntu.default.path'
  'DESKTOP_SESSION'='ubuntu'
  'DISPLAY'=':0'
  'GDMSESSION'='ubuntu'
  'GDM_LANG'='en_US'
  'GEM_HOME'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/.gems'
  'GEM_PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/.gems:/home/dfki.uni-bremen.de/lmedagoda/.gem/ruby/1.9.1:/var/lib/gems/1.9.1:/usr/share/rubygems-integration/1.9.1:/usr/share/rubygems-integration/all'
  'GNOME_DESKTOP_SESSION_ID'='this-is-deprecated'
  'GNOME_KEYRING_CONTROL'='/run/user/1545611510/keyring-qL7noF'
  'GNOME_KEYRING_PID'='1985'
  'GPG_AGENT_INFO'='/run/user/1545611510/keyring-qL7noF/gpg:0:1'
  'GTK_IM_MODULE'='ibus'
  'GTK_MODULES'='overlay-scrollbar:unity-gtk-module'
  'HOME'='/home/dfki.uni-bremen.de/lmedagoda'
  'IM_CONFIG_PHASE'='1'
  'INSTANCE'='Unity'
  'JOB'='gnome-session'
  'KRB5CCNAME'='FILE:/tmp/krb5cc_1545611510_bOioIV'
  'LANG'='en_US.UTF-8'
  'LC_ADDRESS'='en_AU.UTF-8'
  'LC_IDENTIFICATION'='en_AU.UTF-8'
  'LC_MEASUREMENT'='en_AU.UTF-8'
  'LC_MONETARY'='en_AU.UTF-8'
  'LC_NAME'='en_AU.UTF-8'
  'LC_NUMERIC'='C'
  'LC_PAPER'='en_AU.UTF-8'
  'LC_TELEPHONE'='en_AU.UTF-8'
  'LC_TIME'='en_AU.UTF-8'
  'LD_LIBRARY_PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/lib'
  'LOGNAME'='lmedagoda'
  'MANDATORY_PATH'='/usr/share/gconf/ubuntu.mandatory.path'
  'OLDPWD'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools'
  'ORBInitRef'='NameService=corbaname::127.0.0.1'
  'OROCOS_TARGET'='gnulinux'
  'OROGEN_PLUGIN_PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/orogen_ros/lib/orogen_ros/plugin.rb:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/share/orogen/plugins'
  'OSG_FILE_PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/share/vizkit'
  'PAPERSIZE'='a4'
  'PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/metaruby/bin:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/orogen/bin:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/log_tools/bin:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/roby/bin:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/pocolog/bin:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/orocos.rb/bin:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/syskit/bin:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/base/scripts/bin:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/rubigen/bin:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/gui/vizkit/bin:/usr/lib/icecc/bin:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/bin:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/.gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dfki.uni-bremen.de/lmedagoda/Downloads/eclipse'
  'PKG_CONFIG_PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/lib/pkgconfig:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/lib64/pkgconfig'
  'PWD'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf'
  'PYTHONPATH'=''
  'PYTHONUSERBASE'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/.pip'
  'QT4_IM_MODULE'='xim'
  'QT_IM_MODULE'='ibus'
  'QT_PLUGIN_PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/lib/qt'
  'QT_QPA_PLATFORMTHEME'='appmenu-qt5'
  'ROBY_PLUGIN_PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/syskit/lib/syskit/roby_app/register_plugin.rb:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/base/scripts/lib/rock/roby_plugin.rb'
  'ROCK_BUNDLE_PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/bundles:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/share/rock'
  'ROCK_FORCE_FLAVOR'='stable'
  'ROCK_PREFIX'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/share/rock'
  'ROCK_TEMPLATE_PREFIX'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/base/templates/'
  'ROCK_TEMPLATE_SUFFIX'=''
  'ROCK_WEBAPP'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/share/rest_api'
  'RTT_COMPONENT_PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/lib/orocos/plugins'
  'RUBYLIB'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/utilrb/lib:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/metaruby/lib:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/orogen/lib:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/log_tools/lib:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/roby/lib:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/pocolog/lib:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/orocos.rb/lib:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/syskit/lib:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/base/scripts/lib:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/rubigen/lib:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/gui/vizkit/lib:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/lib/ruby/1.9.1/x86_64-linux:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/lib/ruby/1.9.1:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/simulation/orogen/avalon_simulation/ruby:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/slam/envire/ruby:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/drivers/transformer/ruby/lib'
  'RUBYOPT'='-rubygems'
  'SELINUX_INIT'='YES'
  'SESSIONTYPE'='gnome-session'
  'SHELL'='/bin/bash'
  'SHLVL'='1'
  'SSH_AUTH_SOCK'='/run/user/1545611510/keyring-qL7noF/ssh'
  'TERM'='xterm'
  'TEXTDOMAIN'='im-config'
  'TEXTDOMAINDIR'='/usr/share/locale/'
  'TYPELIB_RUBY_PLUGIN_PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/share/typelib/ruby'
  'UPSTART_EVENTS'='started starting'
  'UPSTART_INSTANCE'=''
  'UPSTART_JOB'='unity-settings-daemon'
  'UPSTART_SESSION'='unix:abstract=/com/ubuntu/upstart-session/1545611510/1988'
  'USER'='lmedagoda'
  'USERNAME'='lmedagoda'
  'VIZKIT_PLUGIN_RUBY_PATH'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/lib/vizkit:/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install/lib'
  'VTE_VERSION'='3409'
  'WINDOWID'='86000600'
  'WINDOWPATH'='7'
  'XAUTHORITY'='/var/run/gdm/auth-for-lmedagoda-32T84z/database'
  'XDG_CONFIG_DIRS'='/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg'
  'XDG_CURRENT_DESKTOP'='Unity'
  'XDG_DATA_DIRS'='/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/'
  'XDG_RUNTIME_DIR'='/run/user/1545611510'
  'XDG_SEAT'='seat0'
  'XDG_SESSION_ID'='c2'
  'XDG_VTNR'='7'
  'XMODIFIERS'='@im=ibus'
  '_'='/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/.gems/bin/amake'

2015-08-17 17:19:34 +0200: running
    cmake -DCMAKE_INSTALL_PREFIX=/home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/install -DCMAKE_MODULE_PATH= -DRUBY_EXECUTABLE=/usr/bin/ruby1.9.1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON /home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/service_discovery
in directory /home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/service_discovery/build
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/lib/icecc/bin/cc
-- Check for working C compiler: /usr/lib/icecc/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/icecc/bin/c++
-- Check for working CXX compiler: /usr/lib/icecc/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'sigc++-2.0'
--   found sigc++-2.0, version 2.2.10
/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include
-I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include
-- Boost version: 1.54.0
-- Using the following Boost include directory: /usr/local/include
-- Found the following Boost libraries:
--   regex: /usr/lib/x86_64-linux-gnu/libboost_regex.so
--   system: /usr/local/lib/libboost_system-mt.so
-- Performing Test CXX_SUPPORTS_Wall
-- Performing Test CXX_SUPPORTS_Wall - Success
-- Performing Test CXX_SUPPORTS_Wno_unused_local_typedefs
-- Performing Test CXX_SUPPORTS_Wno_unused_local_typedefs - Success
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- checking for module 'sigc++-2.0'
--   found sigc++-2.0, version 2.2.10
-- checking for module 'base-lib'
--   found base-lib, version 0.1
-- checking for module 'avahi-client'
--   found avahi-client, version 0.6.31
-- checking for module 'avahi-core'
--   found avahi-core, version 0.6.31
-- checking for module 'dbus-1'
--   found dbus-1, version 1.6.18
-- Boost version: 1.54.0
-- Using the following Boost include directory: /usr/local/include
-- Found the following Boost libraries:
--   unit_test_framework: /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so
-- FindRuby: looking for config.h
-- Found Ruby: /usr/bin/ruby1.9.1  
-- did not find Yard, the Ruby packages won't generate documentation
-- Ruby library found: /usr/lib/libruby-1.9.1.so
-- found Ruby version 1.9.3
-- checking for module 'base-lib'
--   found base-lib, version 0.1
-- checking for module 'sigc++-2.0'
--   found sigc++-2.0, version 2.2.10
-- Found GEM: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/service_discovery/build

From install/log/tools/service_discovery-build.log:

2015-08-17 16:11:24 +0200: running
    make --jobserver-fds=5,6 -j
in directory /home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/service_discovery/build
[  5%] [ 11%] Building CXX object src/CMakeFiles/service_discovery.dir/impl/avahi/ServiceBrowser.cpp.o
Building CXX object src/CMakeFiles/service_discovery.dir/impl/avahi/ServiceDiscovery.cpp.o
In file included from /usr/local/include/boost/atomic.hpp:12:0,
                 from /usr/local/include/boost/thread/pthread/once_atomic.hpp:20,
                 from /usr/local/include/boost/thread/once.hpp:20,
                 from /usr/local/include/boost/thread.hpp:17,
                 from /home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/service_discovery/src/impl/avahi/ServiceBrowser.hpp:16,
                 from /home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/service_discovery/src/impl/avahi/ServiceBrowser.cpp:1:
/usr/local/include/boost/atomic/atomic.hpp:202:16: error: ‘uintptr_t’ was not declared in this scope
 typedef atomic<uintptr_t> atomic_uintptr_t;
                ^
/usr/local/include/boost/atomic/atomic.hpp:202:25: error: template argument 1 is invalid
 typedef atomic<uintptr_t> atomic_uintptr_t;
                         ^
/usr/local/include/boost/atomic/atomic.hpp:202:43: error: invalid type in declaration before ‘;’ token
 typedef atomic<uintptr_t> atomic_uintptr_t;
                                           ^
In file included from /usr/local/include/boost/atomic.hpp:12:0,
                 from /usr/local/include/boost/thread/pthread/once_atomic.hpp:20,
                 from /usr/local/include/boost/thread/once.hpp:20,
                 from /usr/local/include/boost/thread.hpp:17,
                 from /home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/service_discovery/src/impl/avahi/ServiceDiscovery.hpp:6,
                 from /home/dfki.uni-bremen.de/lmedagoda/flatfish/buildconf/tools/service_discovery/src/impl/avahi/ServiceDiscovery.cpp:1:
/usr/local/include/boost/atomic/atomic.hpp:202:16: error: ‘uintptr_t’ was not declared in this scope
 typedef atomic<uintptr_t> atomic_uintptr_t;
                ^
/usr/local/include/boost/atomic/atomic.hpp:202:25: error: template argument 1 is invalid
 typedef atomic<uintptr_t> atomic_uintptr_t;
                         ^
/usr/local/include/boost/atomic/atomic.hpp:202:43: error: invalid type in declaration before ‘;’ token
 typedef atomic<uintptr_t> atomic_uintptr_t;
                                           ^
make[2]: *** [src/CMakeFiles/service_discovery.dir/impl/avahi/ServiceBrowser.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/service_discovery.dir/impl/avahi/ServiceDiscovery.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/service_discovery.dir/all] Error 2
make: *** [all] Error 2

**Comment by 2maz** [comment]
You seem to have multiple versions of boost installed -- this is asking for trouble.
Right now cmake is picking the includes from /usr/local/include/ and the libs from /usr/lib.
Best fix is to remove the custom boost installation and rely on ubuntu's default installation.

**Comment by lmedagoda** [comment]
Ah yes that is the problem. When I was trying to compile some of the boost libraries with multithreading support, and that happened. That version was still 1.54 though. I just checked with Sascha, and the boost 1.54 version for ubuntu is on his computer, but the cstdint.hpp file is not the version on the boost website for 1.54. You can see that version here: http://www.boost.org/doc/libs/1_54_0/boost/cstdint.hpp

Perhaps ubuntu patched 1.54 to the 1.55 version of cstdint.hpp, and kept the 1.54 version of boost otherwise, to deal with having glibc 2.19.
